### PR TITLE
enum messages: Make the returned values all 'static

### LINKED ISSUE #159: Lifetimes overly-strict in EnumMessage
```
pub trait EnumMessage {
    fn get_message(&self) -> Option<&str>;
    fn get_detailed_message(&self) -> Option<&str>;
    fn get_serializations(&self) -> &[&str];
}
```

But these strings (and the array from `get_serializations`) are all static - literatls in attributes.  The returned lifetimes should promise `'static` rather than borrowing the lifetime of some owned enum.

### PR DESCRIPTION
**Pull request by ijackson**
This is (at least in theory) a breaking change, because someone might
have implemented this trait by hand, and their implementation won't
be declared as returning 'static lifetimes.

Closes #159

### CODE REVIEW

**Comment by ijackson** [comment]
The Travis failure seems unrelated:

```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)

   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/enum_variant_type-0.2.1/src/lib.rs:144:1

    |

144 | extern crate alloc;

    | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.

error: Could not compile `enum_variant_type`.
```

**Comment by Peternator7** [comment]
Fixed the build with #162, could you merge master and re-push?

This seems generally useful to me so I'm okay taking the small chance of breaking existing code.

**Comment by ijackson** [comment]
The AppVeyor failure is this:
```
verbose: creating temp file: C:\Users\appveyor\.rustup\tmp\5vzkbz8b4rvu6tfk_file
verbose: creating temp file: C:\Users\appveyor\.rustup\tmp\5wypi_xgi7diffwp_file
verbose: deleted temp directory: C:\Users\appveyor\.rustup\tmp\b658ydoei39unwji_dir
info: installing component 'rust-std'
verbose: creating temp directory: C:\Users\appveyor\.rustup\tmp\h32i514dflmtq_j2_dir
memory allocation of 16777216 bytes failed
Command exited with code -1073740791
```
The error code is 0xffffffffc0000409.  No idea what that means.  I don't think this is related to my changes.

**Comment by Peternator7** [comment]
Appveyor has been flakey lately. Re-running fixed the gate

**Pull request merged**
