### PR TITLE
fix for field not method complaint in strum_macro's metadata.rs

### PR DESCRIPTION
**Pull request by hlmtre**
[see](https://i.imgur.com/1k131PE.png)

### CODE REVIEW

**Comment by Peternator7** [comment]
Interesting, do you know what `syn` version you're using? `value()` was added to syn around `1.0.61` [Docs](https://docs.rs/syn/1.0.61/syn/struct.LitBool.html) [Commit](https://github.com/dtolnay/syn/commit/b2f1da284d666ec59571033807f46a8c082330cb#diff-ce4e3f87da05491a74818b9736b02d9c40274befb1e2c13f44c6995eb001b925)

I'm fine accepting this since it appears it will improve compatibility, but there might be an opportunity for another plugin to use a newer version of syn here as well.

**Comment by hlmtre** [comment]
[cargo tree](https://i.imgur.com/AF0U9aw.png) and [inverted, selecting for `syn`](https://i.imgur.com/xnWcr74.png). it appears it's being pulled 'first' for `serde_derive`, which, even on the most recent `master` commit 20 days ago, depends tantalizingly closely on 1.0.60.

i ain't gonna be the guy that suggests a project as big and scary as `serde` update their `syn` dependency :cold_sweat:

**Comment by Peternator7** [comment]
How disappointing! This is an easy enough workaround though and lower stakes than updating serde-derive as you said, so I'll go ahead and merge this change in.

**Comment by hlmtre** [comment]
Thank you!

**Pull request merged**
