### PR TITLE
Implement `get_int`/`get_bool` for properties

### PR DESCRIPTION
**Pull request by marxin**
Fixes: #313

I am also suggesting to use `i64` as return type for `get_int` in order to cover also negative numbers.

### CODE REVIEW

**Comment by Peternator7** [comment]
Hey @marxin, thanks for the PR! This has been requested for quite a while. I tend to agree with @pali6 though that this would probably be better if accepted literals of the expected type rather than parsing the string.

In some ideal world, we could accept an expression `#[strum(props(my_prop = true || false))]` but that's difficult because we'd need to figure out the type. I think a better solution in the first version is to change the grammar so that `Prop` parses a [`Lit`](https://docs.rs/syn/latest/syn/enum.Lit.html) rather than a `LitStr` then we can do a pattern match in the macro to figure out what type of property we're looking at.

**Comment by marxin** [comment]
Here we go. I've implemented the suggested approach for the two functions. Eventually, I decided to track the 3 categories using HashMap in `enum_properties_inner`, but using arrays (the original commit in this PR) might be possible. Which approach do you prefer?

**Comment by Peternator7** [comment]
Looks great to me! thanks for taking the time to work on this :)

**Comment by marxin** [comment]
Thanks for merging. May I ask you whether you plan to choke a new release any time soon?

**Comment by Milo123459** [comment]
bump - @Peternator7 any plans for a new release soon?

**Comment by Peternator7** [comment]
@Milo123459 You might've seen already but 0.27 has this change

**Pull request merged**
