### PR TITLE
implement From<Enum> for &'static str in case of AsStaticRef derive

### LINKED ISSUE #38: RFC: Use instead (in addition) to strum::AsStaticStr  core::convert::Into trait ?
What about generates something like:

```Rust
        impl Into<&'static str> for $Name {
            fn into(self) -> &'static str {
                match self {
                    $($Name::$Variant => $StrVar),*
                }
            }
        }
```

instead of `strum::AsStaticStr` or in additional to `strum::AsStaticStr`?

### PR DESCRIPTION
**Pull request by Dushistov**
fix #38

### CODE REVIEW

**Comment by Peternator7** [comment]
This is great! I'd say this is the way that it should've been done in the first place :) 

Here's my thoughts - when possible, I try and make it so someone can use `strum_macros` without `strum` itself. Rather than implement `From` in the same derive as AsStaticRef, can we make a separate custom derive that implements `From<Enum>` using `match x { (arms)* }`. That way there's no dependency on strum types and you can just import the macros :).

Then we'll work on deprecating `AsStaticRef`, but I'm not sure what the proper way of deprecating a procedural macro is.

**Comment by Dushistov** [comment]
> Rather than implement From in the same derive as AsStaticRef, can we make a separate custom derive > that implements From<Enum> using match x { (arms)* }. That way there's no dependency on strum 
> types and you can just import the macros :).

I changed implementation as you suggested. I named new derive as `IntoStaticStr`,
yes it implements `From`  trait, but it purpose to convert into `&'static str`.

> Then we'll work on deprecating AsStaticRef, but I'm not sure what the proper way of deprecating a 
> procedural macro is.

I suppose it is enough to add deprecation note to trait (see my last comment) and user will see deprecation note.

**Comment by Peternator7** [comment]
Merged!! Thanks for the PR. I'll work on getting this pushed to crates.

**Comment by blacktemplar** [comment]
Why does `IntoStaticStr` deprecate `AsStaticRef`? What about the use case that I have a reference to an enum that does not implement `Copy` and I want to get a `&'static str` representation for it?

**Comment by Peternator7** [comment]
`IntoStaticStr` should probably implement `From<&'a Enum> for &'static str` in addition to (or instead of) taking the enum by value so you can use it for types that are not copy.

**Pull request merged**
