### PR TITLE
Feature/21/serialize all

### LINKED ISSUE #21: Feature request: `serialize_all = "snake_case"`
It would be great to have a `serialize_all` feature à la serde `rename_all`. https://serde.rs/container-attrs.html

This crate may be interesting: https://crates.io/crates/heck

Maybe with a spec and some insight, I might try to do it myself if I found the time.

### PR DESCRIPTION
**Pull request by azriel91**
Closes #21.

Added a changelog as well, since I find that useful

### CODE REVIEW

**Comment by Peternator7** [comment]
Thanks for taking this!! I'll try and get it reviewed by this weekend :)

**Comment by Peternator7** [comment]
Both your PR's look good. :) Thanks for proactively helping out with this!! I appreciate it a lot. I think I'll squash this then merge your second PR. Does that sound good to you?

**Comment by azriel91** [comment]
That does sound good :slightly_smiling_face:, but before that I'd like to do two more things:

* Add `impl From<MyEnum> for MyEnumDiscriminants`
* Fix a typo that I just noticed: "followign"

shall do that now

**Comment by azriel91** [comment]
okay cool all done! Not sure which level of squashing you prefer (like, squash both branches or each one individually), but squash away!

**Comment by Peternator7** [comment]
I completed the 2nd PR because I was worried about conflicts, and I think it had all your changes. If that's correct, let's go ahead and close this PR. Otherwise let me know!

**Comment by azriel91** [comment]
Yeap it did, thank you! hi5 ✋

**Pull request closed without merging**
