### PR TITLE
strum_macros: absolutize type paths

### PR DESCRIPTION
**Pull request by durka**
This commit changes all the type paths in quoted code to be absolute, so the expanded code works in modules and in case stdlib types are shadowed (e.g. a local `Result` alias).

### CODE REVIEW

**Comment by Peternator7** [comment]
These changes look good! Thanks for the PR

**Comment by durka** [comment]
Awesome! When you have a chance could you publish a new version so I can put my crate (that relies on this fix) up on crates.io?

**Comment by Peternator7** [comment]
I'll get it pushed tonight, and add a comment here when it's published!

**Comment by Peternator7** [comment]
strum v0.2.0 is out.  Thanks for your contribution :)

**Comment by durka** [comment]
foreman v0.2.1 is out!

**Pull request merged**
