### PR TITLE
Update strum to Rust edition 2018

### LINKED ISSUE #109: Convert to Rust edition 2018?
According to `README.md`, the MSRV for strum is 1.31, which is the version that introduced the 2018 edition. Would a PR updating the code base to the new edition be welcome?

### PR DESCRIPTION
**Pull request by jplatte**
Fixes #109.

I've updated the docs too (removing the mentions of `extern crate`), is that okay?

### CODE REVIEW

**Comment by Peternator7** [comment]
Thanks for opening the PR :) It looks like the build failures are legit, and there's probably some missing usings in the test cases. I'll be good to merge this once we fix the build.

**Comment by jplatte** [comment]
Huh, so really the way to solve this would be changing `#[cfg(feature = "derive")]` on the macro re-exports to `#[cfg(any(feature = "derive", doctest))]`, but that [doesn't work](https://github.com/rust-lang/rust/issues/67295). Alternatively CI could only run tests with `--all-features`, but that seems like a pretty bad idea. WDYT?

**Comment by jplatte** [comment]
@Peternator7 friendly ping.

**Comment by Peternator7** [comment]
I was poking around with this locally, and it looks to me like it works if I call `cargo test` from the root of the repository (the workspace) but fails if it's run from any of the subprojects. Can you confirm whether that behavior works for you?

If that's the case, we might be able to just update the appveyor script to call `cargo test` from the repo root instead of needing to step in and out of each of the projects.

**Comment by jplatte** [comment]
Yes, by calling `cargo test` from the workspace root the strum derive feature is enabled because it is required by another workspace member. `cargo test --features derive` or `cargo test --all-features` inside the strum directory should work too. Do your okay with doctests boot working without that feature turned on?

**Comment by Peternator7** [comment]
So I think I'm okay with that. The only people really running the tests should be contributors to this repo, and I would expect the most natural thing for someone to do is build the workspace and that works as expected. I pushed some changes last night that fixed the build and started actively building 1.31 for appveyor.

The gates on this PR pass now so let me review the content, but we should be good wrt the build.

**Review by Peternator7 — APPROVED** [review]

**Pull request merged**
