### PR TITLE
Update to heck 0.4

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
It's the 1.32 builds that are failing, but I don't think they're related to this PR?

**Comment by Peternator7** [comment]
Looks good! Agree that the error looks unrelated. Let me fix the build and then we can get this merged :)

**Comment by Peternator7** [comment]
Tests pass locally after fixing the dependency version. Thanks for the update

**Comment by alex** [comment]
Thanks!

**Pull request merged**
